### ISSUE TITLE
Add smart handling of stone vs deepslate

### ISSUE THREAD

**Issue by wingzero54** [CivMC/HiddenOre#9]
With the new height change, below y0 you have Deepslate instead of stone, with deepslate ore variants for each ore. Currently I have duplicated the hiddenore config to have a set of normal ore drops, and a second set of deepslate ore drops. This has also required have a set of veins for normal ores, and a second set of veins for deepslate ore drops.

It would be really nice if Hiddenore could know that Deepslate -> Deepslate ores and Stone -> ores.

**Comment by ProgrammerDan** [comment]
While I can understand the thought process here, Deepslate != Stone, and the ores in each class are distinct block types. Adding meta knowledge that automatically applies reduces configurable control, it does not increase configurable control. If we added something to HiddenOre, like custom meta classes of types, it's a new Technical Debt every time Mojang adds a new ore type, especially as Deepslate ores and Stone ores eventually fully diverge with unique ore types in each zone.

I'd strongly recommend just closing this ticket as at least if I were maintainer, this feels like extra code complexity with no actual benefit.

Better to spend some effort creating a visual configurator to make defining valid HiddenOre configs less painful, as frankly the current situation is not great and never has been. It's massively powerful but like you indicate, consequently "large".

In any case, clever use of aggregate style drop configurations (a set of triggers with a set of valid transforms) with clever Y banding in your drops defined in the dropList, should let you have a single set of drops (one for each literal ore block) with a unified percentages model, banded by Y and one relatively simple aggregate drop configuration for deepslate, and another for stone. This would support veins as normal, since veins are defined in the drops.

Apologies for the essay, but I fear hidden "auto aggregation" would increase plugin complexity while reducing configurable control.
